repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: isort
        language: python
        types: [ python ]
        exclude: .+/(dist|.venv|venv|build)/.+
        pass_filenames: true
      - id: black
        name: black-local
        entry: black
        language: python
        types: [ python ]
        exclude: .+/(dist|.venv|venv|build)/.+
        pass_filenames: true
